name: First Python CI
on: 
    push:
        branches: main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout repository first"
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.13'
            
          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pytest

          - name: "Run the Test"
            run: pytest
